# Generated by Django 5.0.7 on 2024-08-06 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_comment='Электронная почта', max_length=255, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(db_comment='Имя пользователя', max_length=255, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(db_comment='Фамилия пользователя', max_length=255, verbose_name='Фамилия пользователя')),
                ('middle_name', models.CharField(db_comment='Отчество пользователя', max_length=255, verbose_name='Отчество пользователя')),
                ('date_birthday', models.DateField(blank=True, db_comment='День рождения', null=True, verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, db_comment='Телефон', max_length=15, null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, db_comment='Аватар пользователя', default='media/users/avatar/avatar_default.png', null=True, upload_to='users/avatar/', verbose_name='Аватар пользователя')),
                ('is_client', models.BooleanField(db_comment='Флаг клиента', default=False, verbose_name='Флаг клиента')),
                ('is_employee', models.BooleanField(db_comment='Флаг работника', default=False, verbose_name='Флаг работника')),
                ('is_banned', models.BooleanField(db_comment='Флаг бана', default=False, verbose_name='Флаг бана')),
                ('is_active', models.BooleanField(db_comment='Флаг активности', default=True, verbose_name='Флаг активности')),
                ('is_staff', models.BooleanField(db_comment='Флаг персонала', default=False, verbose_name='Флаг персонала')),
                ('is_superuser', models.BooleanField(db_comment='Флаг админа', default=False, verbose_name='Флаг админа')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': '_us_users',
                'db_table_comment': 'Пользователи',
                'ordering': ['pk'],
            },
        ),
    ]
