# Generated by Django 5.0.7 on 2024-08-06 13:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceСategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название категории услуг', max_length=255, verbose_name='Название категории услуг')),
                ('description', models.TextField(db_comment='Описание категории услуг', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'db_table': '_ca_categories',
                'db_table_comment': 'Справочная информация о категориях услуг',
                'ordering': ['title'],
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='ServiceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Название услуги', max_length=255, unique=True, verbose_name='Название услуги')),
                ('general_info', models.TextField(blank=True, db_comment='Общая информация об услуге', null=True, verbose_name='Общая информация')),
                ('additional_info', models.TextField(blank=True, db_comment='Дополнительная информация об услуге', null=True, verbose_name='Дополнительная информация')),
                ('duration', models.DurationField(db_comment='Продолжительность оказания услуги', default=datetime.timedelta(days=1), verbose_name='Продолжительность услуги')),
                ('preparation', models.TextField(blank=True, db_comment='Требования к подготовке оказания услуги', null=True, verbose_name='Требования к подготовке')),
                ('price', models.PositiveIntegerField(db_comment='Стоимость, руб.', verbose_name='Стоимость, руб.')),
                ('discount', models.IntegerField(db_comment='Скидка, проценты', default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, проценты')),
                ('categories', models.ManyToManyField(related_name='categories', to='catalog.serviceсategories', verbose_name='Категории услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': '_ca_service_info',
                'db_table_comment': 'Справочная информация о предоставляемой услуге',
                'ordering': ['title'],
                'unique_together': {('title',)},
            },
        ),
    ]
