# Generated by Django 5.0.7 on 2024-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.PositiveIntegerField(db_comment='ID работника', verbose_name='ID работника')),
                ('job_title', models.CharField(db_comment='Должность работника', max_length=255, verbose_name='Должность работника')),
                ('specializations', models.CharField(db_comment='Специализация', max_length=255, verbose_name='Специализация')),
                ('experience', models.DurationField(db_comment='Опыт работы', verbose_name='Опыт работы')),
                ('education', models.CharField(db_comment='Образование', max_length=255, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'db_table': '_us_employees',
                'db_table_comment': 'Работники',
                'ordering': ['id_employee'],
            },
        ),
    ]
