# Generated by Django 5.0.7 on 2024-08-06 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(blank=True, db_comment='Клиент', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registredservices',
            name='client',
            field=models.ForeignKey(db_comment='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.clients', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='registredservices',
            name='doctor',
            field=models.ForeignKey(blank=True, db_comment='Доктор', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='Доктор'),
        ),
        migrations.AddField(
            model_name='registredservices',
            name='service',
            field=models.ForeignKey(db_comment='Услуга', on_delete=django.db.models.deletion.DO_NOTHING, related_name='service', to='catalog.serviceinformation', verbose_name='Услуга'),
        ),
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('passport_id',)},
        ),
    ]
